version: '2.3'

services:
    app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
        tty: true
        volumes:
            - .:/usr/src
        ports:
            - "5000:5000"